# apps/sealed-secrets/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add this section to apply the annotation to all resources,
# including the Application resource that Autopilot will create.
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  # 显式地从 Sealed Secrets 的官方 GitHub 仓库中拉取并应用 CRD 文件。
  # 这一行强制 Kustomize 将 CRD 作为部署的一部分，解决了 CRD 被忽略的问题。
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/refs/tags/v0.31.0/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml

# This section tells Kustomize to render and apply a Helm chart
helmCharts:
- name: sealed-secrets
  # This is the official Helm repo URL from the README
  repo: https://bitnami-labs.github.io/sealed-secrets
  # It's best practice to pin to a specific chart version
  version: "2.17.3"
  releaseName: sealed-secrets
  namespace: kube-system
  # (Optional but recommended) Point to a values file for custom configuration
  valuesFile: values.yaml
