# ==============================================================================
# Custom Values for NFS CSI Driver on Homelab Cluster
# ==============================================================================

# -- Controller Configuration --
# The controller handles the logic of creating/deleting volumes (PVs).
controller:
  # For a small homelab cluster, 1 replica is sufficient.
  replicas: 1

  # Best Practice: Place the controller pod on the control-plane node.
  # Your y9000p node has this label.
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

# -- StorageClass Configuration --
# We will let the Helm chart create and manage the StorageClass for us.
storageClass:
  # Enable creation of the StorageClass.
  create: true

 # 为 StorageClass 命名
  name: nfs-csi

  # SRE 最佳实践：将回收策略设置为 Retain
  # 这意味着当您删除一个 PVC 时，底层 NFS 目录中的数据将被保留，防止意外删除
  reclaimPolicy: Retain

  # 最佳实践：延迟卷绑定直到第一个 Pod 被调度
  # 这允许调度器在决定在哪个节点上创建卷时考虑 Pod 的约束
  volumeBindingMode: WaitForFirstConsumer

  # (可选，但推荐) 允许未来对 PVC 进行在线扩容
  allowVolumeExpansion: true

  # 指向您的 NFS 服务器的具体参数
  parameters:
    server: "192.168.50.94"  # 您的 NFS 服务器 IP (b360m)
    share: "/mnt/nas/"        # 您在 b360m 上 exports 的共享路径

  # 推荐的 NFS 挂载选项，以确保稳定性和性能
  mountOptions:
    - "hard"
    - "nfsvers=4.1"
