# apps/ragflow/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1. 引用您创建的、包含所有密码的加密文件
  - sealed-ragflow-credentials.yaml

helmCharts:
  # 2. 定义要部署的 RAGFlow Helm Chart
  - name: ragflow
    # 这是最关键的部分：
    # 我们使用 'go-getter' 的语法来精确定位到 Git 仓库中的子目录。
    # - "https://github.com/infiniflow/ragflow.git/" 是仓库地址。
    # - "//helm" 表示仓库根目录下的 'helm' 子目录。
    # - "?ref=main" 指定了使用 'main' 分支。
    repo: "https://github.com/infiniflow/ragflow.git//helm?ref=main"
    releaseName: ragflow
    valuesFile: values.yaml

# 3. 定义一系列补丁，将统一的 Secret 注入到不同的 Deployment 中
patches:
  # 补丁 A: 为 RAGFlow 主服务的 Deployment 注入所有需要的密码
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef: { name: ragflow-credentials, key: mysql-password }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MINIO_PASSWORD
          valueFrom:
            secretKeyRef: { name: ragflow-credentials, key: minio-password }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef: { name: ragflow-credentials, key: redis-password }
    target:
      kind: Deployment
      name: ragflow-ragflow

  # 补丁 B: 为 MySQL Deployment 注入 MySQL 密码
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef: { name: ragflow-credentials, key: mysql-password }
    target:
      kind: Deployment
      name: ragflow-mysql

  # 补丁 C: 为 MinIO Deployment 注入 MinIO 密码
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: { name: ragflow-credentials, key: minio-password }
    target:
      kind: Deployment
      name: ragflow-minio

  # 补丁 D: 为 Redis Deployment 注入 Redis 密码
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef: { name: ragflow-credentials, key: redis-password }
    target:
      kind: Deployment
      name: ragflow-redis
