apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ragflow-application.yaml
  # Your sealed secret still lives here alongside the application definition
  - sealed-ragflow-credentials.yaml

# Your patches are now managed by the Application spec itself,
# so they should be removed from here.
patches: []

# This is no longer needed here.
helmCharts: []
