apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: csi-driver-nfs
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  version: v4.11.0
  releaseName: csi-driver-nfs
  valuesFile: csi-driver-nfs-values.yaml
